"""create telemetry records

Revision ID: 0d9f238a438b
Revises: 
Create Date: 2026-09-26 20:06:51.405733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9f238a438b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_meters', sa.Float(), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('bearing_degrees', sa.Float(), nullable=True),
    sa.Column('accelerometer_x', sa.Float(), nullable=False),
    sa.Column('accelerometer_y', sa.Float(), nullable=False),
    sa.Column('accelerometer_z', sa.Float(), nullable=False),
    sa.Column('gyroscope_x', sa.Float(), nullable=False),
    sa.Column('gyroscope_y', sa.Float(), nullable=False),
    sa.Column('gyroscope_z', sa.Float(), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.Column('network_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_device_id'), 'telemetry_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_records_timestamp'), 'telemetry_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_records_timestamp'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_device_id'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    # ### end Alembic commands ###
